name:                happy-history
version:             0.1.0.0
github:              jazcarate/happy-history
license:             Unlicense
author:              Joaquin Azcarate
maintainer:          j@florius.com.ar
copyright:           2021 Joaquin Azcarate

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Navigate though history and re-use commands with ease
category:            Command Line
description:         Please see the README on Github at <https://github.com/jazcarate/happy-history#readme>

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude

dependencies:
- base
- rio
- text
- ansi-terminal
- process
- read-editor

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans

library:
  source-dirs: src

executables:
  hh:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - happy-history
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  happy-history-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - happy-history
    - QuickCheck
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
